# Generated by Django 2.0.7 on 2018-08-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='female', max_length=10),
        ),
    ]
