# Generated by Django 2.0.7 on 2018-08-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Female', max_length=10),
        ),
    ]
