# Generated by Django 2.0.7 on 2018-08-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20180805_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Bottom', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Female', max_length=10),
        ),
    ]
