# Generated by Django 2.0.7 on 2018-08-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_auto_20180805_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='5 6 6.5 7 7.5 8 8.5 9 9.5', max_length=60),
        ),
    ]
