# Generated by Django 2.0.7 on 2018-08-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_auto_20180805_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='7 8 9 9.5 10 10.5 11 12 13 14', max_length=60),
        ),
    ]
