# Generated by Django 2.0.7 on 2018-08-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_auto_20180806_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
