# Generated by Django 2.0.7 on 2018-08-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
